version: "3.9"

services:

  server:
    build: ./TFT-Friendly.Back
    restart: on-failure
    ports:
      - 8080:5000
    environment:
      ASPNETCORE_URLS: "http://+:5000"
      ASPNETCORE_ENVIRONMENT: "Development"
    links:
      - database
    depends_on:
        - database

  database:
    container_name: database
    image: mongo
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - database-data:/data/db

volumes:
  database-data:
